kind=defined
names=assert_raise
visibility=public

--- assert_raise(klass1, klass2, ..., message = "") { ... }    -> object

ブロックを実行して例外が発生し、その例外が
klass1, klass2,... のいずれかのクラスのインスタンスならばパスします。

assert にパスした時は、実際に投げられた例外を返します。

@raise Test::Unit::AssertionFailedError assert が失敗した時に発生します。


