kind=defined
names=assert_nothing_thrown
visibility=public

--- assert_nothing_thrown(message="") { ... }    -> ()

ブロックを実行して throw が起こらなければパスします。

@raise Test::Unit::AssertionFailedError assert が失敗した時に発生します。

